### ISSUE TITLE
Travis

### ISSUE THREAD

**Issue by buruska97** [BME-MIT-IET/GibHup-iet-2019#2]
Travist kell kapcsolni a kódhoz

**Comment by buruska97** [comment]
Kész, a Travis fut, továbbra sem fordul le a program a maven build miatt.

**Comment by gr4cza** [comment]
https://github.com/travis-ci/travis-ci/issues/8199 e szerint nem is lehet már 1.6-os javával Travist futtatni.

**Comment by gr4cza** [comment]
a #8  megoldva.

**Comment by gr4cza** [comment]
a #8 megoldja
