### ISSUE TITLE
Kódjavítás

### ISSUE THREAD

**Issue by buruska97** [BME-MIT-IET/GibHup-iet-2019#3]
A Codacy által javasolt hibákat javítsuk ki és csináljunk pull requestet a kijavított hibák elfogadására

**Comment by buruska97** [comment]
#5 Pullrequest egy ilyen.

**Comment by Gbor97** [comment]
Javítottam néhány Codacy által javasolt hibát, review is történt. Pullrequest: https://github.com/BME-MIT-IET/GibHup-iet-2019/pull/6
