### ISSUE TITLE
Projekt leírást készíteni.

### ISSUE THREAD

**Issue by gr4cza** [BME-MIT-IET/GibHup-iet-2019#7]
A feladat megoldásához szükséges egy projekt leírást készíteni.

**Comment by gr4cza** [comment]
Hozzá adtam pár dolgot f1e53794658259dcce2377e202fd483e51aba426

**Comment by Gbor97** [comment]
Írtam dolgokat én is

**Comment by gr4cza** [comment]
Nem ez a pontos feladat, #10 pontosítja, ezt zárom.
